### ISSUE TITLE
Getting error in the Runbook Test pane

### ISSUE THREAD

**Issue by g2901b** [Cj-Scott/Get-AppRegistrationExpiration#5]
The runbook is failing with the below error while I am testing the runbook in the test pane.  Any idea? 

"Failed
System.Management.Automation.CommandNotFoundException: The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) (System.Management.Automation.CommandNotFoundException: The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame))"

**Comment by Cj-Scott** [comment]
It looks like you may not have the Az module loaded in your azure automation workspace. Or it is not up to date?

you could modify the candlers for arm modules or import the Az cmdlets. They don’t work well together though so take precautions to make sure it’s a clean migration from one to the other if that’s the route you choose.

**Comment by g2901b** [comment]
Still getting the same error even after importing the Azure modules to the Automation account. Would you mind for us to connect and have a screen sharing session just to see if I am missing something here. Please let me know if that is a possibility. Thanks

**Comment by Cj-Scott** [comment]
You may need to add the import module command to the runbook as well, importing the module into the account does not automatically import the module into the sandbox where the PSSession is run.

if you DM me your email I’ll will reach out and try and schedule some time to look over your situation.

**Comment by g2901b** [comment]
Scott, could you please let me know the run schedule. Is it Daily/Weekly/Monthly and what time it will run? So far, I have only received email notification once in last 2 days. Also, will it provide the list of all Apps expiring within 30 days everytime it runs or only the 1st time and then skip the next list onwards. I have integrated it with the incident ticketing tool and would prefer not to receive the same App in the list every time it runs as that will create multiple duplicate tickets for the same App.

**Comment by Cj-Scott** [comment]
Youll need to set the runbook to run on a schedule. The schedule and the alerts should be configured to best suit your organizations needs. The runbook does not track prior reported accounts but instead keeps a running list so you can track how long it took too remediate. If you need to only report new accounts you would have to build a tracking mechanism in the code.
